# Project Metadata
project_name: "telco customer churn"
version: 1.0

data :
 path : '../data/Telco_customer_churn.xlsx'
 model : '../model/Telco_customer_churn.pkl'
 remove_columns : ['Lat_Long','Zip_Code','Churn_Reason','Count','Latitude','Longitude','Total_Charges','Churn_Value','CLTV','CustomerID','Country','State','Streaming_Movies']
 objective: "binary:logistic"
 eval_metric: "logloss"
 n_estimators: 1000
 max_depth: 3
 learning_rate : 0.01
 subsample: 1
 colsample_bytree: 1
 n_jobs: -1
 tree_method: "hist"
 reg_alpha: 0.01
 reg_lambda: 0.0
 random_state : 42
 test_size : 0.30
 n_splits: 10
 